# Generated by Django 5.1 on 2024-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0002_shoppingitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
