# Generated by Django 5.1 on 2024-08-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0003_alter_shoppingitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
