# Generated by Django 5.1 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pronumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
