# Generated by Django 4.0.2 on 2024-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0006_products_shop_alter_products_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('authentificationCode', models.CharField(max_length=100)),
            ],
        ),
    ]
