# Generated by Django 4.0.2 on 2024-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0008_alter_user_authentificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authentificationCode',
            field=models.IntegerField(null=True),
        ),
    ]
