# Generated by Django 4.0.2 on 2024-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasarDerksen', '0009_alter_user_authentificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_happy_hour', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='price_happy_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
